import type { Metadata } from "next";
import { Inter, Lexend_Deca } from "next/font/google";
import "./globals.css";

const lexendDeca = Lexend_Deca({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "3 column preview card component",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexendDeca.className}>
        <main className="flex flex-col justify-center items-center min-h-screen  bg-gray-100">
          {children}
        </main>
      </body>
    </html>
  );
}
